# Generated by Django 4.0.4 on 2022-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blancos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=200)),
                ('subcategoria', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cocina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=200)),
                ('subcategoria', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=200)),
                ('subcategoria', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
